/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMyJobsRouteImport } from './routes/_authenticated/my-jobs'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs.$jobId'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin.jobs'
import { Route as AuthenticatedAdminContactsRouteImport } from './routes/_authenticated/admin.contacts'
import { Route as AuthenticatedAdminChecklistsRouteImport } from './routes/_authenticated/admin.checklists'
import { Route as AuthenticatedAdminAreasRouteImport } from './routes/_authenticated/admin.areas'
import { Route as ApiPublicHighlevelContactRouteImport } from './routes/api/public/highlevel/contact'
import { Route as ApiPublicHighlevelAppointmentRouteImport } from './routes/api/public/highlevel/appointment'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyJobsRoute = AuthenticatedMyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContactsRoute =
  AuthenticatedAdminContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChecklistsRoute =
  AuthenticatedAdminChecklistsRouteImport.update({
    id: '/checklists',
    path: '/checklists',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAreasRoute = AuthenticatedAdminAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicHighlevelContactRoute =
  ApiPublicHighlevelContactRouteImport.update({
    id: '/api/public/highlevel/contact',
    path: '/api/public/highlevel/contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHighlevelAppointmentRoute =
  ApiPublicHighlevelAppointmentRouteImport.update({
    id: '/api/public/highlevel/appointment',
    path: '/api/public/highlevel/appointment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/my-jobs': typeof AuthenticatedMyJobsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/checklists': typeof AuthenticatedAdminChecklistsRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/highlevel/appointment': typeof ApiPublicHighlevelAppointmentRoute
  '/api/public/highlevel/contact': typeof ApiPublicHighlevelContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/my-jobs': typeof AuthenticatedMyJobsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/checklists': typeof AuthenticatedAdminChecklistsRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/highlevel/appointment': typeof ApiPublicHighlevelAppointmentRoute
  '/api/public/highlevel/contact': typeof ApiPublicHighlevelContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/my-jobs': typeof AuthenticatedMyJobsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/_authenticated/admin/checklists': typeof AuthenticatedAdminChecklistsRoute
  '/_authenticated/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/highlevel/appointment': typeof ApiPublicHighlevelAppointmentRoute
  '/api/public/highlevel/contact': typeof ApiPublicHighlevelContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/admin'
    | '/my-jobs'
    | '/settings'
    | '/today'
    | '/admin/areas'
    | '/admin/checklists'
    | '/admin/contacts'
    | '/admin/jobs'
    | '/admin/settings'
    | '/admin/team'
    | '/jobs/$jobId'
    | '/admin/'
    | '/api/public/highlevel/appointment'
    | '/api/public/highlevel/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/my-jobs'
    | '/settings'
    | '/today'
    | '/admin/areas'
    | '/admin/checklists'
    | '/admin/contacts'
    | '/admin/jobs'
    | '/admin/settings'
    | '/admin/team'
    | '/jobs/$jobId'
    | '/admin'
    | '/api/public/highlevel/appointment'
    | '/api/public/highlevel/contact'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/my-jobs'
    | '/_authenticated/settings'
    | '/_authenticated/today'
    | '/_authenticated/admin/areas'
    | '/_authenticated/admin/checklists'
    | '/_authenticated/admin/contacts'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/team'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/admin/'
    | '/api/public/highlevel/appointment'
    | '/api/public/highlevel/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  ApiPublicHighlevelAppointmentRoute: typeof ApiPublicHighlevelAppointmentRoute
  ApiPublicHighlevelContactRoute: typeof ApiPublicHighlevelContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-jobs': {
      id: '/_authenticated/my-jobs'
      path: '/my-jobs'
      fullPath: '/my-jobs'
      preLoaderRoute: typeof AuthenticatedMyJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contacts': {
      id: '/_authenticated/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AuthenticatedAdminContactsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/checklists': {
      id: '/_authenticated/admin/checklists'
      path: '/checklists'
      fullPath: '/admin/checklists'
      preLoaderRoute: typeof AuthenticatedAdminChecklistsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/areas': {
      id: '/_authenticated/admin/areas'
      path: '/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AuthenticatedAdminAreasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/highlevel/contact': {
      id: '/api/public/highlevel/contact'
      path: '/api/public/highlevel/contact'
      fullPath: '/api/public/highlevel/contact'
      preLoaderRoute: typeof ApiPublicHighlevelContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/highlevel/appointment': {
      id: '/api/public/highlevel/appointment'
      path: '/api/public/highlevel/appointment'
      fullPath: '/api/public/highlevel/appointment'
      preLoaderRoute: typeof ApiPublicHighlevelAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAreasRoute: typeof AuthenticatedAdminAreasRoute
  AuthenticatedAdminChecklistsRoute: typeof AuthenticatedAdminChecklistsRoute
  AuthenticatedAdminContactsRoute: typeof AuthenticatedAdminContactsRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAreasRoute: AuthenticatedAdminAreasRoute,
  AuthenticatedAdminChecklistsRoute: AuthenticatedAdminChecklistsRoute,
  AuthenticatedAdminContactsRoute: AuthenticatedAdminContactsRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMyJobsRoute: typeof AuthenticatedMyJobsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMyJobsRoute: AuthenticatedMyJobsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  ApiPublicHighlevelAppointmentRoute: ApiPublicHighlevelAppointmentRoute,
  ApiPublicHighlevelContactRoute: ApiPublicHighlevelContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
